name: orchid
channels:
  - 'https://repo.continuum.io/pkgs/free'
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python == 3.9
  - numpy
  - tqdm
  - nltk
  - jupyter
  - pytorch
  - pip
  - pip:
    - black
    - pathlib
    - dataclasses
    - mypy
    - transformers
    - apex
    - pytest
    - python-dotenv
    - tensorboard
    - scipy
