name: orchid
chanels:
  - anaconda
dependencies:
  - python == 3.8.0
  - numpy
  - tqdm
  - nltk
  - jupyter
  - pytorch
  - pip:
    - black
    - pathlib
    - dataclasses
    - mypy
    - transformers
    - apex
