name: orchid
channels:
  - anaconda
dependencies:
  - python == 3.8.12
  - numpy
  - tqdm
  - nltk
  - jupyter
  - pytorch
  - cudatoolkit == 11.3
  - pip:
    - black
    - pathlib
    - dataclasses
    - mypy
    - transformers
    - apex
    - pytest
    - python-dotenv
    - tensorboard
    - scipy
